name: GDExtension Build

on: [push, pull_request]

jobs:
  build:
    name: Build ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            artifact-pattern: PlanarReflector-CPP/addons/PlanarReflectorCpp/bin/libPlanarReflectorCPP.linux.*.so
          - os: windows-latest
            platform: windows
            artifact-pattern: PlanarReflector-CPP/addons/PlanarReflectorCpp/bin/PlanarReflectorCPP.windows.*.dll
          - os: macos-latest
            platform: macos
            artifact-pattern: PlanarReflector-CPP/addons/PlanarReflectorCpp/bin/PlanarReflectorCPP.macos.*.framework/**

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install SCons
        run: pip install scons

      - name: Setup Windows Compiler (MSVC)
        if: matrix.platform == 'windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile GDExtension Binaries
        run: |
          scons platform=${{ matrix.platform }} target=template_debug -j 4
          scons platform=${{ matrix.platform }} target=template_release -j 4

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: PlanarReflectorCpp-${{ matrix.platform }}
          path: |
            ${{ matrix.artifact-pattern }}
            PlanarReflector-CPP/addons/PlanarReflectorCpp/bin/PlanarReflectorCpp.gdextension

  merge:
    name: Merge all platforms
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: PlanarReflectorCpp-all-platforms
          pattern: PlanarReflectorCpp-*
